version: '3.3'

services:
   centos:
     depends_on:
       - db
     build: centos/.
     ports:
       - "80:8080"
     volumes:
       - ./html:/var/www/html
       - ./cu-multitenant:/var/www/multitenant
     restart: always
     environment:
      DB_HOST: db:3306
      DB_NAME: default
      DB_USER: default
      DB_PASSWORD: secret
   db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: default
       MYSQL_USER: default
       MYSQL_PASSWORD: secret 
volumes:
    db_data: